- hosts: lb
  become: True
  tasks:
    - name: configure nginx rpm
      yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: start and enable
      service:
        name: nginx
        state: started
        enabled: True
    - name: copy nginx.conf to nginx server
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx    
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

